type Alternativa {
  correta: Boolean!
  enunciado: String!
  id: ID!
}

type CasoClinico {
  enunciado: String!
  id: ID!
  questoesObjetivas: [QuestaoObjetiva!]!
}

type Mutation {
  createCasoClinico(enunciado: String!): CasoClinico!
}

type Query {
  casoClinico(id: Int!): CasoClinico!
  casosClinicos: [CasoClinico!]!
}

type QuestaoObjetiva {
  alternativas: [Alternativa!]!
  enunciado: String!
  id: ID!
}