import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Providers from "./providers"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/authOptions"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Enso",
  description: "Generated by create next app"
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="pt-BR">
      <body className={inter.className} suppressHydrationWarning>
        <Providers session={session}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
